########################################
#
#  GLOBAL VARIABLES
#
########################################

@baseUrl=http://localhost:{{$dotenv APP_PORT_EXTERNAL}}/api
@accept=application/json
@contentType=application/json

########################################
#
#  AUTHORIZATION
#
########################################

### Login / Access Token Generation
# @name authLogin

POST {{baseUrl}}/auth/login
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "email": "default@app.com",
    "password": "defaultpassword"
}

### Access Token Definition

@accessToken={{authLogin.response.body.data.access_token}}

# To delete tokens, you can use this code on Laravel Tinker: \App\Domain\User\Models\User::find(1)->tokens()->delete();

### Get Authenticated User Data
# @name authMe

GET {{baseUrl}}/auth/me
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  FARE
#
########################################

### Get List Of Fares

GET {{baseUrl}}/fares
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  PLAN
#
########################################

### Get List Of Plans

GET {{baseUrl}}/plans
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  CALL PRICE
#
########################################

### Simulate call price

POST {{baseUrl}}/call-prices/simulate
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "ddd_origin": "011",
    "ddd_destination": "016",
    "call_minutes": 20,
    "plan_id": 1
}

### Simulate call price

POST {{baseUrl}}/call-prices/simulate
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "ddd_origin": "011",
    "ddd_destination": "017",
    "call_minutes": 80,
    "plan_id": 2
}

### Simulate call price

POST {{baseUrl}}/call-prices/simulate
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "ddd_origin": "018",
    "ddd_destination": "011",
    "call_minutes": 200,
    "plan_id": 3
}